// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.23.4
// source: stats-api.proto

package protobuff

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QubicData struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Timestamp                int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CirculatingSupply        int64                  `protobuf:"varint,2,opt,name=circulating_supply,json=circulatingSupply,proto3" json:"circulating_supply,omitempty"`
	ActiveAddresses          int32                  `protobuf:"varint,3,opt,name=active_addresses,json=activeAddresses,proto3" json:"active_addresses,omitempty"`
	Price                    float32                `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	MarketCap                int64                  `protobuf:"varint,5,opt,name=market_cap,json=marketCap,proto3" json:"market_cap,omitempty"`
	Epoch                    uint32                 `protobuf:"varint,6,opt,name=epoch,proto3" json:"epoch,omitempty"`
	CurrentTick              uint32                 `protobuf:"varint,7,opt,name=current_tick,json=currentTick,proto3" json:"current_tick,omitempty"`
	TicksInCurrentEpoch      uint32                 `protobuf:"varint,8,opt,name=ticks_in_current_epoch,json=ticksInCurrentEpoch,proto3" json:"ticks_in_current_epoch,omitempty"`
	EmptyTicksInCurrentEpoch uint32                 `protobuf:"varint,9,opt,name=empty_ticks_in_current_epoch,json=emptyTicksInCurrentEpoch,proto3" json:"empty_ticks_in_current_epoch,omitempty"`
	EpochTickQuality         float32                `protobuf:"fixed32,10,opt,name=epoch_tick_quality,json=epochTickQuality,proto3" json:"epoch_tick_quality,omitempty"`
	BurnedQus                uint64                 `protobuf:"varint,11,opt,name=burned_qus,json=burnedQus,proto3" json:"burned_qus,omitempty"`
	TicksInLast10000         uint32                 `protobuf:"varint,12,opt,name=ticks_in_last10000,json=ticksInLast10000,proto3" json:"ticks_in_last10000,omitempty"`
	EmptyTicksInLast10000    uint32                 `protobuf:"varint,13,opt,name=empty_ticks_in_last10000,json=emptyTicksInLast10000,proto3" json:"empty_ticks_in_last10000,omitempty"`
	Last10000TickQuality     float32                `protobuf:"fixed32,14,opt,name=last10000_tick_quality,json=last10000TickQuality,proto3" json:"last10000_tick_quality,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *QubicData) Reset() {
	*x = QubicData{}
	mi := &file_stats_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QubicData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QubicData) ProtoMessage() {}

func (x *QubicData) ProtoReflect() protoreflect.Message {
	mi := &file_stats_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QubicData.ProtoReflect.Descriptor instead.
func (*QubicData) Descriptor() ([]byte, []int) {
	return file_stats_api_proto_rawDescGZIP(), []int{0}
}

func (x *QubicData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *QubicData) GetCirculatingSupply() int64 {
	if x != nil {
		return x.CirculatingSupply
	}
	return 0
}

func (x *QubicData) GetActiveAddresses() int32 {
	if x != nil {
		return x.ActiveAddresses
	}
	return 0
}

func (x *QubicData) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *QubicData) GetMarketCap() int64 {
	if x != nil {
		return x.MarketCap
	}
	return 0
}

func (x *QubicData) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *QubicData) GetCurrentTick() uint32 {
	if x != nil {
		return x.CurrentTick
	}
	return 0
}

func (x *QubicData) GetTicksInCurrentEpoch() uint32 {
	if x != nil {
		return x.TicksInCurrentEpoch
	}
	return 0
}

func (x *QubicData) GetEmptyTicksInCurrentEpoch() uint32 {
	if x != nil {
		return x.EmptyTicksInCurrentEpoch
	}
	return 0
}

func (x *QubicData) GetEpochTickQuality() float32 {
	if x != nil {
		return x.EpochTickQuality
	}
	return 0
}

func (x *QubicData) GetBurnedQus() uint64 {
	if x != nil {
		return x.BurnedQus
	}
	return 0
}

func (x *QubicData) GetTicksInLast10000() uint32 {
	if x != nil {
		return x.TicksInLast10000
	}
	return 0
}

func (x *QubicData) GetEmptyTicksInLast10000() uint32 {
	if x != nil {
		return x.EmptyTicksInLast10000
	}
	return 0
}

func (x *QubicData) GetLast10000TickQuality() float32 {
	if x != nil {
		return x.Last10000TickQuality
	}
	return 0
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalRecords  int32                  `protobuf:"varint,1,opt,name=total_records,json=totalRecords,proto3" json:"total_records,omitempty"`
	CurrentPage   int32                  `protobuf:"varint,2,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	TotalPages    int32                  `protobuf:"varint,3,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_stats_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_stats_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_stats_api_proto_rawDescGZIP(), []int{1}
}

func (x *Pagination) GetTotalRecords() int32 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

func (x *Pagination) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *Pagination) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type RichListEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Balance       int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RichListEntity) Reset() {
	*x = RichListEntity{}
	mi := &file_stats_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RichListEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RichListEntity) ProtoMessage() {}

func (x *RichListEntity) ProtoReflect() protoreflect.Message {
	mi := &file_stats_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RichListEntity.ProtoReflect.Descriptor instead.
func (*RichListEntity) Descriptor() ([]byte, []int) {
	return file_stats_api_proto_rawDescGZIP(), []int{2}
}

func (x *RichListEntity) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *RichListEntity) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type RichList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*RichListEntity      `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RichList) Reset() {
	*x = RichList{}
	mi := &file_stats_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RichList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RichList) ProtoMessage() {}

func (x *RichList) ProtoReflect() protoreflect.Message {
	mi := &file_stats_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RichList.ProtoReflect.Descriptor instead.
func (*RichList) Descriptor() ([]byte, []int) {
	return file_stats_api_proto_rawDescGZIP(), []int{3}
}

func (x *RichList) GetEntities() []*RichListEntity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type GetRichListSliceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Page  int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// Value must be between 1 and 100
	PageSize      int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRichListSliceRequest) Reset() {
	*x = GetRichListSliceRequest{}
	mi := &file_stats_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRichListSliceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRichListSliceRequest) ProtoMessage() {}

func (x *GetRichListSliceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRichListSliceRequest.ProtoReflect.Descriptor instead.
func (*GetRichListSliceRequest) Descriptor() ([]byte, []int) {
	return file_stats_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetRichListSliceRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetRichListSliceRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetRichListSliceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *Pagination            `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Epoch         uint32                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	RichList      *RichList              `protobuf:"bytes,3,opt,name=rich_list,json=richList,proto3" json:"rich_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRichListSliceResponse) Reset() {
	*x = GetRichListSliceResponse{}
	mi := &file_stats_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRichListSliceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRichListSliceResponse) ProtoMessage() {}

func (x *GetRichListSliceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRichListSliceResponse.ProtoReflect.Descriptor instead.
func (*GetRichListSliceResponse) Descriptor() ([]byte, []int) {
	return file_stats_api_proto_rawDescGZIP(), []int{5}
}

func (x *GetRichListSliceResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetRichListSliceResponse) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *GetRichListSliceResponse) GetRichList() *RichList {
	if x != nil {
		return x.RichList
	}
	return nil
}

type GetAssetOwnershipRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IssuerIdentity string                 `protobuf:"bytes,1,opt,name=issuer_identity,json=issuerIdentity,proto3" json:"issuer_identity,omitempty"`
	AssetName      string                 `protobuf:"bytes,2,opt,name=asset_name,json=assetName,proto3" json:"asset_name,omitempty"`
	Page           uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize       uint32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAssetOwnershipRequest) Reset() {
	*x = GetAssetOwnershipRequest{}
	mi := &file_stats_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetOwnershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetOwnershipRequest) ProtoMessage() {}

func (x *GetAssetOwnershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetOwnershipRequest.ProtoReflect.Descriptor instead.
func (*GetAssetOwnershipRequest) Descriptor() ([]byte, []int) {
	return file_stats_api_proto_rawDescGZIP(), []int{6}
}

func (x *GetAssetOwnershipRequest) GetIssuerIdentity() string {
	if x != nil {
		return x.IssuerIdentity
	}
	return ""
}

func (x *GetAssetOwnershipRequest) GetAssetName() string {
	if x != nil {
		return x.AssetName
	}
	return ""
}

func (x *GetAssetOwnershipRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAssetOwnershipRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetAssetOwnershipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *Pagination            `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Tick          uint32                 `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
	Owners        []*AssetOwnership      `protobuf:"bytes,3,rep,name=owners,proto3" json:"owners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetOwnershipResponse) Reset() {
	*x = GetAssetOwnershipResponse{}
	mi := &file_stats_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetOwnershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetOwnershipResponse) ProtoMessage() {}

func (x *GetAssetOwnershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetOwnershipResponse.ProtoReflect.Descriptor instead.
func (*GetAssetOwnershipResponse) Descriptor() ([]byte, []int) {
	return file_stats_api_proto_rawDescGZIP(), []int{7}
}

func (x *GetAssetOwnershipResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetAssetOwnershipResponse) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *GetAssetOwnershipResponse) GetOwners() []*AssetOwnership {
	if x != nil {
		return x.Owners
	}
	return nil
}

type AssetOwnership struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Identity       string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	NumberOfShares int64                  `protobuf:"varint,2,opt,name=number_of_shares,json=numberOfShares,proto3" json:"number_of_shares,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AssetOwnership) Reset() {
	*x = AssetOwnership{}
	mi := &file_stats_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetOwnership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetOwnership) ProtoMessage() {}

func (x *AssetOwnership) ProtoReflect() protoreflect.Message {
	mi := &file_stats_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetOwnership.ProtoReflect.Descriptor instead.
func (*AssetOwnership) Descriptor() ([]byte, []int) {
	return file_stats_api_proto_rawDescGZIP(), []int{8}
}

func (x *AssetOwnership) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *AssetOwnership) GetNumberOfShares() int64 {
	if x != nil {
		return x.NumberOfShares
	}
	return 0
}

type GetLatestDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *QubicData             `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestDataResponse) Reset() {
	*x = GetLatestDataResponse{}
	mi := &file_stats_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestDataResponse) ProtoMessage() {}

func (x *GetLatestDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestDataResponse.ProtoReflect.Descriptor instead.
func (*GetLatestDataResponse) Descriptor() ([]byte, []int) {
	return file_stats_api_proto_rawDescGZIP(), []int{9}
}

func (x *GetLatestDataResponse) GetData() *QubicData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_stats_api_proto protoreflect.FileDescriptor

const file_stats_api_proto_rawDesc = "" +
	"\n" +
	"\x0fstats-api.proto\x12\x12qubic.stats.api.pb\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xd0\x04\n" +
	"\tQubicData\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12-\n" +
	"\x12circulating_supply\x18\x02 \x01(\x03R\x11circulatingSupply\x12)\n" +
	"\x10active_addresses\x18\x03 \x01(\x05R\x0factiveAddresses\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x02R\x05price\x12\x1d\n" +
	"\n" +
	"market_cap\x18\x05 \x01(\x03R\tmarketCap\x12\x14\n" +
	"\x05epoch\x18\x06 \x01(\rR\x05epoch\x12!\n" +
	"\fcurrent_tick\x18\a \x01(\rR\vcurrentTick\x123\n" +
	"\x16ticks_in_current_epoch\x18\b \x01(\rR\x13ticksInCurrentEpoch\x12>\n" +
	"\x1cempty_ticks_in_current_epoch\x18\t \x01(\rR\x18emptyTicksInCurrentEpoch\x12,\n" +
	"\x12epoch_tick_quality\x18\n" +
	" \x01(\x02R\x10epochTickQuality\x12\x1d\n" +
	"\n" +
	"burned_qus\x18\v \x01(\x04R\tburnedQus\x12,\n" +
	"\x12ticks_in_last10000\x18\f \x01(\rR\x10ticksInLast10000\x127\n" +
	"\x18empty_ticks_in_last10000\x18\r \x01(\rR\x15emptyTicksInLast10000\x124\n" +
	"\x16last10000_tick_quality\x18\x0e \x01(\x02R\x14last10000TickQuality\"\x92\x01\n" +
	"\n" +
	"Pagination\x12#\n" +
	"\rtotal_records\x18\x01 \x01(\x05R\ftotalRecords\x12!\n" +
	"\fcurrent_page\x18\x02 \x01(\x05R\vcurrentPage\x12\x1f\n" +
	"\vtotal_pages\x18\x03 \x01(\x05R\n" +
	"totalPages\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"F\n" +
	"\x0eRichListEntity\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance\"J\n" +
	"\bRichList\x12>\n" +
	"\bentities\x18\x01 \x03(\v2\".qubic.stats.api.pb.RichListEntityR\bentities\"J\n" +
	"\x17GetRichListSliceRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\xab\x01\n" +
	"\x18GetRichListSliceResponse\x12>\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1e.qubic.stats.api.pb.PaginationR\n" +
	"pagination\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\rR\x05epoch\x129\n" +
	"\trich_list\x18\x03 \x01(\v2\x1c.qubic.stats.api.pb.RichListR\brichList\"\x93\x01\n" +
	"\x18GetAssetOwnershipRequest\x12'\n" +
	"\x0fissuer_identity\x18\x01 \x01(\tR\x0eissuerIdentity\x12\x1d\n" +
	"\n" +
	"asset_name\x18\x02 \x01(\tR\tassetName\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\rR\bpageSize\"\xab\x01\n" +
	"\x19GetAssetOwnershipResponse\x12>\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1e.qubic.stats.api.pb.PaginationR\n" +
	"pagination\x12\x12\n" +
	"\x04tick\x18\x02 \x01(\rR\x04tick\x12:\n" +
	"\x06owners\x18\x03 \x03(\v2\".qubic.stats.api.pb.AssetOwnershipR\x06owners\"V\n" +
	"\x0eAssetOwnership\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12(\n" +
	"\x10number_of_shares\x18\x02 \x01(\x03R\x0enumberOfShares\"J\n" +
	"\x15GetLatestDataResponse\x121\n" +
	"\x04data\x18\x01 \x01(\v2\x1d.qubic.stats.api.pb.QubicDataR\x04data2\xb5\x03\n" +
	"\fStatsService\x12l\n" +
	"\rGetLatestData\x12\x16.google.protobuf.Empty\x1a).qubic.stats.api.pb.GetLatestDataResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/latest-stats\x12\x84\x01\n" +
	"\x10GetRichListSlice\x12+.qubic.stats.api.pb.GetRichListSliceRequest\x1a,.qubic.stats.api.pb.GetRichListSliceResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/rich-list\x12\xaf\x01\n" +
	"\x0eGetAssetOwners\x12,.qubic.stats.api.pb.GetAssetOwnershipRequest\x1a-.qubic.stats.api.pb.GetAssetOwnershipResponse\"@\x82\xd3\xe4\x93\x02:\x128/v1/issuers/{issuer_identity}/assets/{asset_name}/ownersB-Z+github.com/qubic/qubic-stats-api/protobuff/b\x06proto3"

var (
	file_stats_api_proto_rawDescOnce sync.Once
	file_stats_api_proto_rawDescData []byte
)

func file_stats_api_proto_rawDescGZIP() []byte {
	file_stats_api_proto_rawDescOnce.Do(func() {
		file_stats_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stats_api_proto_rawDesc), len(file_stats_api_proto_rawDesc)))
	})
	return file_stats_api_proto_rawDescData
}

var file_stats_api_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_stats_api_proto_goTypes = []any{
	(*QubicData)(nil),                 // 0: qubic.stats.api.pb.QubicData
	(*Pagination)(nil),                // 1: qubic.stats.api.pb.Pagination
	(*RichListEntity)(nil),            // 2: qubic.stats.api.pb.RichListEntity
	(*RichList)(nil),                  // 3: qubic.stats.api.pb.RichList
	(*GetRichListSliceRequest)(nil),   // 4: qubic.stats.api.pb.GetRichListSliceRequest
	(*GetRichListSliceResponse)(nil),  // 5: qubic.stats.api.pb.GetRichListSliceResponse
	(*GetAssetOwnershipRequest)(nil),  // 6: qubic.stats.api.pb.GetAssetOwnershipRequest
	(*GetAssetOwnershipResponse)(nil), // 7: qubic.stats.api.pb.GetAssetOwnershipResponse
	(*AssetOwnership)(nil),            // 8: qubic.stats.api.pb.AssetOwnership
	(*GetLatestDataResponse)(nil),     // 9: qubic.stats.api.pb.GetLatestDataResponse
	(*emptypb.Empty)(nil),             // 10: google.protobuf.Empty
}
var file_stats_api_proto_depIdxs = []int32{
	2,  // 0: qubic.stats.api.pb.RichList.entities:type_name -> qubic.stats.api.pb.RichListEntity
	1,  // 1: qubic.stats.api.pb.GetRichListSliceResponse.pagination:type_name -> qubic.stats.api.pb.Pagination
	3,  // 2: qubic.stats.api.pb.GetRichListSliceResponse.rich_list:type_name -> qubic.stats.api.pb.RichList
	1,  // 3: qubic.stats.api.pb.GetAssetOwnershipResponse.pagination:type_name -> qubic.stats.api.pb.Pagination
	8,  // 4: qubic.stats.api.pb.GetAssetOwnershipResponse.owners:type_name -> qubic.stats.api.pb.AssetOwnership
	0,  // 5: qubic.stats.api.pb.GetLatestDataResponse.data:type_name -> qubic.stats.api.pb.QubicData
	10, // 6: qubic.stats.api.pb.StatsService.GetLatestData:input_type -> google.protobuf.Empty
	4,  // 7: qubic.stats.api.pb.StatsService.GetRichListSlice:input_type -> qubic.stats.api.pb.GetRichListSliceRequest
	6,  // 8: qubic.stats.api.pb.StatsService.GetAssetOwners:input_type -> qubic.stats.api.pb.GetAssetOwnershipRequest
	9,  // 9: qubic.stats.api.pb.StatsService.GetLatestData:output_type -> qubic.stats.api.pb.GetLatestDataResponse
	5,  // 10: qubic.stats.api.pb.StatsService.GetRichListSlice:output_type -> qubic.stats.api.pb.GetRichListSliceResponse
	7,  // 11: qubic.stats.api.pb.StatsService.GetAssetOwners:output_type -> qubic.stats.api.pb.GetAssetOwnershipResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_stats_api_proto_init() }
func file_stats_api_proto_init() {
	if File_stats_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stats_api_proto_rawDesc), len(file_stats_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stats_api_proto_goTypes,
		DependencyIndexes: file_stats_api_proto_depIdxs,
		MessageInfos:      file_stats_api_proto_msgTypes,
	}.Build()
	File_stats_api_proto = out.File
	file_stats_api_proto_goTypes = nil
	file_stats_api_proto_depIdxs = nil
}
